spring:
  application:
    name: gateway

server:
  port: 7856

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: "*"

  routes:
    license-service: /license/**

