server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active:
    - native

  cloud:
    config:
      discovery:
        enabled: false
      server:
        encrypt:
          enabled: false
#        git:
#          uri: https://github.com/petrov9/config-service/
#          searchPaths: license-service
        native:
          search-locations: classpath:/config
