server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/petrov9/config-service/
          searchPaths: license-service
#        native:
#          search-locations: file:///Users/Toxa/Desktop/spring-boot/spring-config-server/src/main/resources/config/license-service
