server:
  port: 8080

tracer:
  property: "I AM THE DEFAULT"
spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/funds"
    username: "postgres"
    password: "postgres"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.postgresql.Driver"
  cloud:
    stream:
      bindings:
        input:
          destination: checkerChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

my:
  message: "Hah, it's work!!!"

keycloak:
  realm: "microservices-example-realm"
  auth-server-url: "http://localhost:9080/auth"
  ssl-required: "external"
  resource: "ostock"
  credentials:
    secret: "24343ee5-f121-403d-b46f-2e279a625787"
  use-resource-role-mappings: true
  bearer-only: true

management:
  endpoints:
    web:
      exposure:
        include=*